### ISSUE TITLE
iOS flickering next screen

### ISSUE THREAD

**Issue by Dric0** [elyalvarado/react-navigation-switch-transitioner#4] opened 2018-10-05 21:21 UTC
When transitioning to new screen (for example, going to profile screen in the example code provided), the new screen flicks very quickly and then the animation starts. Happens using the two options (HOC and wrapping screen)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14186326/46560696-1a4d7400-c8cb-11e8-874c-27acf4bdecb3.gif)

On android its working as intended,
Thanks in advance

**Comment by elyalvarado** [comment] 2018-10-07 19:19
Yes, I'm aware of the flickering on the example project however I haven't been able to found why its happening, and it doesn't happen to me when using it in a react-native project without expo.

Are you able to reproduce it without expo? I think it might be an issue somewhere in the dependency stack that has already been solved, but has not yet made it to expo.

**Comment by brentvatne** [comment] 2018-10-24 01:16
I believe this is because the react-native-reanimated dependency is older in expo currently, the next sdk release will update it

**Comment by elyalvarado** [comment] 2018-10-24 02:07
thanks @brentvatne, I thought it might be that. I'm closely tracking the work of @ericvicenti on react-navigation-transitioner to see how much of the API can be replicated for this switch navigator

**Comment by elyalvarado** [comment] 2019-01-27 02:52
This should be fixed now with the latest version of the library and expo. Please let me know if you're still seeing this behavior.

**Closed by elyalvarado** 2019-01-27 02:52 UTC
